export const sentences = [
  '<Ich> <glaube>, dass <du> <recht> hast.',
  '<Er> <sagt>, dass <es> <regnen> wird.',
  '<Wir> <wissen>, dass <sie> <kommen> wird.',
  '<Ich> <hoffe>, dass <du> <gut> <schläfst>.',
  '<Sie> <hat> <Angst>, dass <er> <nicht> <kommt>.',
  '<Wir> <gehen> <nach> <Hause>, weil <es> <spät> ist.',
  '<Er> <konnte> <nicht> <spielen>, weil <er> <krank> war.',
  '<Wenn> <es> <schneit>, <bleibe> <ich> <zu> <Hause>.',
  '<Ich> <mag> <das> Lied, weil <es> <schön> ist.',
  '<Du> <musst> <lernen>, wenn <du> <bestehen> <willst>.',
  '<Ich> <freue> <mich>, dass <wir> <uns> <sehen>.',
  '<Wenn> <ich> <Zeit> habe, <lese> <ich> <ein> Buch.',
  '<Es> <ist> wichtig, dass <du> <früh> <kommst>.',
  '<Ich> <bin> glücklich, weil <du> <hier> bist.',
  '<Sie> <fragt>, ob <du> <mit> <kommst>.',
  '<Ich> <verstehe> <nicht>, warum <er> <so> <schüchtern> ist.',
  '<Du> <weißt>, dass <wir> <alle> <arbeiten> müssen.',
  '<Sie> <lässt> <mich> <wissen>, wann <sie> <kommt>.',
  '<Es> <stört> <mich>, dass <du> <zu> <spät> <bist>.',
  '<Wenn> <ich> <kann>, <helfe> <ich> <dir>.',
  '<Wir> <machen> <eine> Pause, weil <wir> <müde> sind.',
  '<Er> <hat> gesagt, dass <er> <nicht> <kommt>.',
  '<Wenn> <es> <schneit>, <gehen> <wir> <skifahren>.',
  '<Ich> <wünsche> mir, dass <wir> <urlaub> <machen>.',
  '<Wenn> <du> <Zeit> hast, <rufen> <mich> <an>.',
  '<Sie> <vergisst>, dass <wir> <ein> Treffen <haben>.',
  '<Es> <ist> schade, dass <du> <nicht> <kommen> <kannst>.',
  '<Wir> <sind> <glücklich>, dass <alles> <gut> <ist>.',
  '<Ich> <bin> traurig, weil <der> Film <langweilig> war.',
  '<Wenn> <er> <anruft>, <sage> <ihm>, dass <ich> <nicht> <da> bin.',
  '<Sie> <erzählt>, was <sie> <gestern> <gemacht> hat.',
  '<Ich> <weiß>, dass <das> <wichtig> ist.',
  '<Du> <fragst>, ob <ich> <helfen> <kann>.',
  '<Wenn> <es> <regnet>, <bleibe> <ich> <drinnen>.',
  '<Er> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Ich> <glaube>, dass <sie> <sind> <gute> <Freunde>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  '<Sie> <fragt>, ob <wir> <es> <nicht> <schaffen> können.',
  '<Ich> <verstehe>, dass <du> <dich> <nicht> <wohl> fühlst.',
  '<Wenn> <er> <schwimmen> <kann>, <geht> <er> <ins> <Schwimmbad>.',
  '<Es> <interessiert> <mich>, ob <du> <kaufen> <willst>.',
  '<Du> <musst> <schlafen>, wenn <du> <müde> <bist>.',
  '<Wenn> <ich> <gehe>, <kann> <ich> <dich> <anrufen>.',
  '<Wir> <sehen> <uns> <wieder>, wenn <du> <zurück> <kommst>.',
  '<Ich> <freue> mich, dass <wir> <uns> <treffen>.',
  '<Du> <weißt>, dass <sie> <nicht> <schüchtern> ist.',
  '<Sie> <lässt> <ihre> <Freunde> <wissen>, dass <sie> <kommt>.',
  '<Ich> <bin> mir sicher, dass <es> <funktioniert>.',
  '<Wenn> <du> <mich> <brauchst>, <ruf> <mich> <an>.',
  '<Er> <fragt>, ob <ich> <etwas> <mitbringen> <soll>.',
  '<Wir> <wissen>, dass <es> <nicht> <einfach> ist.',
  '<Ich> <verstehe>, warum <sie> <traurig> ist.',
  '<Wenn> <du> <das> <nicht> <magst>, <sag> <es> <mir>.',
  '<Sie> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Wenn> <ich> <zu> <spät> <bin>, <warte> <auf> <mich>.',
  '<Wir> <könnten> <essen>, wenn <du> <hunger> <hast>.',
  '<Ich> <mag> <den> Film, auch wenn <es> <langweilig> <ist>.',
  '<Sie> <will> <wissen>, was <wir> <machen> <werden>.',
  '<Er> <sagt>, dass <wir> <schon> <gehen> <können>.',
  '<Wenn> <du> <das> <brauchst>, <sag> <es> <mir>.',
  '<Ich> <freue> mich, wenn <du> <kommst>.',
  '<Wir> <gehen>, auch wenn <es> <regnet>.',
  '<Sie> <erzählt>, dass <sie> <neue> <Freunde> <gefunden> <hat>.',
  '<Wenn> <es> <nicht> <regnet>, <gehen> <wir> <spazieren>.',
  '<Er> <glaubt>, dass <wir> <es> <schaffen> <werden>.',
  '<Ich> <verstehe>, dass <du> <nicht> <kommst>.',
  '<Wenn> <wir> <fertig> <sind>, <können> <wir> <gehen>.',
  '<Sie> <sagt>, dass <sie> <müde> <ist>.',
  '<Du> <weißt>, dass <ich> <nicht> <gehe>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  '<Er> <hat> gesagt, dass <er> <nicht> <kommt>.',
  '<Wenn> <es> <schneit>, <gehen> <wir> <skifahren>.',
  '<Ich> <wünsche> mir, dass <wir> <urlaub> <machen>.',
  '<Wenn> <du> <Zeit> hast, <rufen> <mich> <an>.',
  '<Sie> <vergisst>, dass <wir> <ein> Treffen <haben>.',
  '<Es> <ist> schade, dass <du> <nicht> <kommen> <kannst>.',
  '<Wir> <sind> <glücklich>, dass <alles> <gut> <ist>.',
  '<Ich> <bin> traurig, weil <der> Film <langweilig> war.',
  '<Wenn> <er> <anruft>, <sage> <ihm>, dass <ich> <nicht> <da> bin.',
  '<Sie> <erzählt>, was <sie> <gestern> <gemacht> hat.',
  '<Ich> <weiß>, dass <das> <wichtig> ist.',
  '<Du> <fragst>, ob <ich> <helfen> <kann>.',
  '<Wenn> <es> <regnet>, <bleibe> <ich> <drinnen>.',
  '<Er> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Ich> <glaube>, dass <sie> <sind> <gute> <Freunde>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  "<Ich> <freue> mich, dass <wir> <zusammen> <arbeiten>.",
  "<Er> <hat> gesagt, dass <er> <morgen> <kommt>.",
  "<Wenn> <du> <mich> <brauchst>, <kannst> <du> <anrufen>.",
  "<Sie> <schreibt>, weil <sie> <sehr> <beschäftigt> <ist>.",
  "<Ich> <finde> es schade, dass <du> <nicht> <mit> <kommen> <kannst>.",
  "<Wenn> <wir> <früh> <gehen>, <kommen> <wir> <rechtzeitig> <an>.",
  "<Sie> <hat> gesagt, dass <sie> <einen> neuen Job <hat>.",
  "<Wenn> <du> <schwimmen> <gehst>, <nehme> <ich> <mein> <Buch> <mit>.",
  "<Ich> <freue> mich, dass <du> <mir> <hilfst>.",
  "<Er> <denkt>, dass <wir> <es> <schaffen> <können>.",
  "<Wenn> <es> <schneit>, <möchte> <ich> <eine> Schneeballschlacht.",
  "<Wir> <essen> <gerne>, während <wir> <fernsehen>.",
  "<Ich> <mag> die Stadt, auch wenn <sie> <sehr> <laut> <ist>.",
  "<Sie> <fragt>, warum <du> <so> <traurig> <bist>.",
  "<Ich> <bin> froh, dass <wir> <uns> <treffen>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <gehen>.",
  "<Er> <sagt>, dass <er> <das> <nicht> <verstanden> <hat>.",
  "<Wenn> <ich> <fertig> <bin>, <gehe> <ich> <nach> <Hause>.",
  "<Wir> <glauben>, dass <es> <eine> gute Entscheidung <ist>.",
  "<Ich> <hoffe>, dass <du> <es> <verstehst>.",
  "<Wenn> <sie> <müde> <ist>, <schläft> <sie> <ein>.",
  "<Er> <sagt>, dass <es> <eine> gute Idee <ist>.",
  "<Wenn> <du> <Zeit> hast, <kannst> <du> <mir> <helfen>.",
  "<Wir> <gehen> <nach> <Hause>, weil <wir> <hungrig> <sind>.",
  "<Ich> <mag> es, wenn <du> <lächelst>.",
  "<Er> <will> wissen, ob <du> <kommst>.",
  "<Wenn> <es> <regnet>, <nehmen> <wir> <einen> Regenschirm.",
  "<Sie> <hat> <gesagt>, dass <sie> <nicht> <essen> <will>.",
  "<Ich> <verstehe>, dass <es> <schwierig> <ist>.",
  "<Wenn> <wir> <gehen>, <wirst> <du> <verpassen>, was <passiert>.",
  "<Er> <hat> <gesagt>, dass <er> <seine> Meinung <ändern> <wird>.",
  "<Ich> <finde> es wichtig, dass <wir> <gemeinsam> <arbeiten>.",
  "<Sie> <freut> sich, dass <wir> <es> <geschafft> <haben>.",
  "<Wenn> <ich> <nicht> <komme>, <werde> <du> <allein> <sein>.",
  "<Er> <denkt>, dass <das> <eine> gute Gelegenheit <ist>.",
  "<Ich> <liebe> es, wenn <du> <lachst>.",
  "<Wenn> <du> <froh> <bist>, <singst> <du> <immer>.",
  "<Wir> <glauben>, dass <wir> <alle> <gemeinsam> <stark> <sind>.",
  "<Wenn> <es> <schneit>, <könnten> <wir> <schlittschuhlaufen>.",
  "<Er> <sagt>, dass <er> <die> Prüfung <bestehen> <wird>.",
  "<Wenn> <du> <mich> <fragst>, <kannst> <du> <es> <wissen>.",
  "<Ich> <bin> froh, dass <wir> <das> <geschafft> <haben>.",
  "<Wenn> <es> <warm> <ist>, <gehen> <wir> <zum> <Strand>.",
  "<Sie> <fragt>, ob <wir> <heute> <spielen> <wollen>.",
  "<Ich> <freue> <mich>, dass <wir> <uns> <treffen>.",
  "<Wenn> <ich> <gehe>, <werde> <ich> <es> <sagen>.",
  "<Er> <sagt>, dass <wir> <es> <versuchen> <sollen>.",
  "<Wenn> <sie> <kommt>, <werde> <ich> <glücklich> <sein>.",
  "<Ich> <verstehe>, dass <du> <angst> <hast>.",
  "<Wenn> <wir> <fertig> <sind>, <könnten> <wir> <essen>.",
  "<Sie> <denkt>, dass <wir> <es> <nicht> <schaffen> <können>.",
  "<Ich> <finde>, dass <das> <interessant> <ist>.",
  "<Wenn> <es> <kalt> <ist>, <ziehe> <ich> <meinen> <Mantel> <an>.",
  "<Er> <hofft>, dass <es> <bald> <aufhört> <zu> <regnen>.",
  "<Ich> <freue> mich, dass <wir> <bald> <kommen> <werden>.",
  "<Wenn> <du> <ein> Problem <hast>, <sag> <es> <mir>.",
  "<Wir> <glauben>, dass <das> <eine> gute Chance <ist>.",
  "<Ich> <verstehe>, wenn <du> <müde> <bist>.",
  "<Wenn> <es> <draußen> <warm> <ist>, <gehen> <wir> <spazieren>.",
  "<Sie> <sagt>, dass <wir> <bald> <gehen> <können>.",
  "<Ich> <freue> mich, wenn <du> <kommst>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <gehen>.",
  "<Er> <denkt>, dass <es> <eine> gute Idee <ist>.",
  "<Wenn> <ich> <fertig> <bin>, <gehe> <ich> <nach> <Hause>.",
  "<Wir> <glauben>, dass <wir> <es> <schaffen> <werden>.",
  "<Ich> <hoffe>, dass <du> <mich> <besuchst>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <sein>.",
  "<Er> <sagt>, dass <es> <eine> gute Entscheidung <ist>.",
  "<Wenn> <ich> <kann>, <helfe> <ich> <dir>.",
  "<Wir> <essen>, während <wir> <fernsehen>.",
  "<Ich> <mag> es, wenn <du> <lächelst>.",
  "<Er> <fragt>, ob <ich> <mit> <kommen> <kann>.",
  "<Wenn> <es> <regnet>, <könnten> <wir> <ein> <Tee> <trinken>.",
  "<Sie> <hat> gesagt, dass <sie> <nicht> <kommt>.",
  "<Ich> <verstehe>, dass <es> <nicht> <einfach> <ist>.",
  "<Wenn> <wir> <gehen>, <wirst> <du> <verpassen>, was <passiert>.",
  "<Er> <hat> <gesagt>, dass <er> <seine> Meinung <ändern> <wird>.",
  "<Ich> <finde> es wichtig, dass <wir> <gemeinsam> <arbeiten>.",
  "<Sie> <freut> sich, dass <wir> <es> <geschafft> <haben>.",
  "<Wenn> <ich> <nicht> <komme>, <werde> <du> <allein> <sein>.",
  "<Er> <denkt>, dass <das> <eine> gute Gelegenheit <ist>.",
  "<Ich> <liebe> es, wenn <du> <lachst>.",
  "<Ich> <weiß>, dass <es> <nicht> <einfach> <ist>.",
  "<Sie> <sagt>, dass <wir> <pünktlich> <sein> <müssen>.",
  "<Wenn> <du> <müde> <bist>, <solltest> <du> <früher> <schlafen> <gehen>.",
  "<Wir> <bleiben> <zu> <Hause>, weil <es> <heute> <regnet>.",
  "<Er> <hat> <erzählt>, dass <er> <gestern> <ein> <Buch> <gelesen> <hat>.",
  "<Ich> <hoffe>, dass <du> <bald> <zurückkommst>.",
  "<Sie> <fragt>, ob <wir> <morgen> <zusammen> <arbeiten> <können>.",
  "<Wenn> <du> <pünktlich> <kommst>, <werden> <wir> <früh> <anfangen>.",
  "<Er> <hat> <vergessen>, dass <er> <den> <Termin> <hat>.",
  "<Ich> <denke>, dass <wir> <bald> <fertig> <sind>.",
  "<Sie> <hofft>, dass <sie> <die> <Prüfung> <besteht>.",
  "<Wenn> <wir> <Glück> <haben>, <könnten> <wir> <früher> <gehen>.",
  "<Er> <sagt>, dass <es> <morgen> <schneien> <wird>.",
  "<Ich> <bin> sicher, dass <wir> <das> <Projekt> <beenden> <werden>.",
  "<Sie> <fragt>, ob <du> <die> <Einladung> <angenommen> <hast>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <es> <allein> <machen>.",
  "<Er> <hat> <mir> gesagt, dass <er> <morgen> <früh> <aufsteht>.",
  "<Ich> <hoffe>, dass <sie> <bald> <anruft>.",
  "<Sie> <hat> <gefragt>, ob <du> <mit> <uns> <fahren> <möchtest>.",
  "<Wenn> <ich> <mehr> <Zeit> <habe>, <werde> <ich> <es> <lesen>.",
  "<Er> <meint>, dass <wir> <das> <so> <machen> <können>.",
  "<Wenn> <wir> <rechtzeitig> <fertig> <sind>, <könnten> <wir> <ins> <Kino> <gehen>.",
  "<Sie> <freut> sich, dass <wir> <zusammen> <arbeiten> <werden>.",
  "<Ich> <glaube>, dass <er> <bald> <zurückkommt>.",
  "<Er> <denkt>, dass <wir> <das> <Problem> <lösen> <können>.",
  "<Wenn> <du> <mehr> <Informationen> <brauchst>, <frag> <mich> <bitte>.",
  "<Ich> <bin> froh, dass <wir> <es> <rechtzeitig> <geschafft> <haben>.",
  "<Sie> <sagt>, dass <sie> <heute> <nicht> <mit> <gehen> <kann>.",
  "<Wenn> <wir> <früh> <aufstehen>, <werden> <wir> <viel> <Zeit> <haben>.",
  "<Ich> <hoffe>, dass <wir> <uns> <bald> <wiedersehen>.",
  "<Er> <fragt>, ob <wir> <morgen> <zusammen> <arbeiten> <können>.",
  "<Wenn> <ich> <mehr> <Zeit> <hätte>, <würde> <ich> <es> <lesen>.",
  "<Sie> <hofft>, dass <wir> <bald> <fertig> <sind>.",
  "<Er> <hat> <erzählt>, dass <er> <heute> <nicht> <mit> <uns> <gehen> <kann>.",
  "<Wenn> <wir> <Glück> <haben>, <wird> <es> <bald> <aufhören> <zu> <regnen>.",
  "<Ich> <weiß>, dass <er> <gestern> <nicht> <da> <war>.",
  "<Er> <sagt>, dass <wir> <später> <losfahren> <können>.",
  "<Sie> <fragt>, warum <du> <so> <spät> <gekommen> <bist>.",
  "<Ich> <hoffe>, dass <sie> <bald> <kommt>.",
  "<Wenn> <du> <mich> <anrufst>, <werde> <ich> <dir> <helfen>.",
  "<Er> <hat> <versprochen>, dass <er> <pünktlich> <sein> <wird>.",
  "<Sie> <meint>, dass <wir> <noch> <etwas> <Zeit> <haben>.",
  "<Wenn> <es> <regnet>, <nehme> <ich> <meinen> <Regenschirm> <mit>.",
  "<Ich> <bin> froh, dass <du> <mir> <geholfen> <hast>.",
  "<Er> <hat> <gesagt>, dass <er> <später> <kommt>.",
  "<Wenn> <wir> <mehr> <Zeit> <hätten>, <könnten> <wir> <länger> <bleiben>.",
  "<Sie> <hat> <erzählt>, dass <sie> <morgen> <nicht> <da> <sein> <wird>.",
  "<Ich> <glaube>, dass <wir> <es> <gemeinsam> <schaffen> <können>.",
  "<Er> <denkt>, dass <es> <heute> <zu> <kalt> <ist>.",
  "<Wenn> <wir> <pünktlich> <anfangen>, <werden> <wir> <rechtzeitig> <fertig>.",
  "<Sie> <sagt>, dass <sie> <müde> <ist>.",
  "<Ich> <hoffe>, dass <wir> <bald> <nach> <Hause> <gehen> <können>.",
  "<Er> <fragt>, ob <wir> <noch> <etwas> <essen> <wollen>.",
  "<Wenn> <du> <fertig> <bist>, <können> <wir> <losgehen>.",
  "<Ich> <denke>, dass <wir> <morgen> <einen> <freien> <Tag> <haben>.",
  "<Er> <hat> <erzählt>, dass <er> <nächste> <Woche> <in> <den> <Urlaub> <fährt>.",
  "<Sie> <sagt>, dass <sie> <nächste> <Woche> <nicht> <da> <sein> <wird>.",
  "<Wenn> <es> <weiter> <regnet>, <werden> <wir> <zu> <Hause> <bleiben>.",
  "<Ich> <bin> sicher, dass <wir> <bald> <fertig> <sind>.",
  "<Er> <hat> <erzählt>, dass <er> <heute> <nicht> <arbeiten> <kann>.",
  "<Sie> <meint>, dass <wir> <die> <Aufgabe> <heute> <noch> <beenden> <sollten>.",
  "<Wenn> <wir> <Glück> <haben>, <könnten> <wir> <das> <Projekt> <vorzeitig> <abschließen>.",
  "<Ich> <glaube>, dass <wir> <eine> <gute> <Chance> <haben>.",
  "<Er> <hofft>, dass <sie> <bald> <anruft>.",
  "<Wenn> <du> <Zeit> <hast>, <komm> <bitte> <vorbei>.",
  "<Ich> <weiß>, dass <du> <mir> <immer> <hilfst>.",
  "<Sie> <hat> <gesagt>, dass <sie> <morgen> <zur> <Arbeit> <gehen> <wird>.",
  "<Er> <fragt>, ob <wir> <später> <zusammen> <essen> <gehen> <können>.",
  "<Wenn> <es> <nicht> <regnet>, <gehen> <wir> <spazieren>.",
  "<Ich> <bin> froh, dass <du> <mir> <geholfen> <hast>.",
  "<Er> <meint>, dass <es> <nicht> <so> <schwierig> <ist>.",
  "<Sie> <hofft>, dass <wir> <uns> <bald> <wiedersehen>.",
  "<Wenn> <wir> <später> <gehen>, <werden> <wir> <die> <Züge> <verpassen>.",
  "<Ich> <glaube>, dass <wir> <es> <noch> <rechtzeitig> <schaffen> <werden>.",
  "<Er> <sagt>, dass <es> <morgen> <sehr> <kalt> <wird>.",
  "<Sie> <fragt>, ob <du> <heute> <noch> <Zeit> <hast>.",
  "<Wenn> <ich> <mehr> <üben> <könnte>, <würde> <ich> <besser> <werden>.",
  "<Er> <hat> <gesagt>, dass <er> <morgen> <später> <kommt>.",
  "<Ich> <denke>, dass <wir> <das> <heute> <noch> <fertig> <kriegen>.",
  "<Sie> <meint>, dass <es> <morgen> <nicht> <regnen> <wird>.",
  "<Wenn> <du> <Zeit> <hast>, <komm> <bitte> <vorbei>.",
  "<Er> <hofft>, dass <er> <bald> <eine> <Antwort> <bekommt>.",
    "🎵 <Du> <hast> <mich> <gefragt>, und <ich> <habe> <nichts> <gesagt>.",
    "🎵 <Ich> <will>, dass <ihr> <mir> <vertraut>.",
    "🎵 <Ich> <will>, dass <ihr> <mir> <glaubt>.",
    "🎵 <Wir> <sind> <voll> <Licht>, aber <sehen> <nichts>.",
    "🎵 <Ich> <habe> <keine> <Lust>, <ich> <habe> <keine> <Lust>.",
    "🎵 <Du> <riechst> <so> <gut>.",
    "🎵 <Ich> <liebe> <dich> <nicht>.",
    "🎵 <Du> <bist> <das> <Feuer>, <ich> <das> <Benzin>.",
    "🎵 <Wir> <werden> <euch> <in> <Staub> <zerlegen>.",
    "🎵 <Ich> <will> <alles>, und <zwar> <sofort>.",
    "🎵 <Der> <Mensch> <ist> <ein> <Tier>, aber <dann> <fressen> <wir> <ihn>.",
    "🎵 <Dein> <Herz> <brennt>, wenn <es> <dich> <versteht>.",
    "🎵 <Mein> <Herz> <brennt>.",
    "🎵 <Ich> <halte> <dich>, wenn <du> <weinst>.",
    "🎵 <Sie> <will> <lieben>, aber <kann> <nicht> <verstehen>.",
    "🎵 <Wenn> <alles> <schläft>, <dann> <werde> <ich> <wachen>.",
    "🎵 <Es> <ist> <nicht> <immer> <leicht>, <ein> <Engel> <zu> <sein>.",
    "🎵 <Du> <hast> <mich> <gefragt>, und <ich> <habe> <nichts> <gesagt>.",
    "🎵 <Ich> <werde> <dich> <verlassen>, wenn <es> <zu> <heiß> <wird>.",
    "🎵 <Du> <bist> <mein> <Verlangen>, <ich> <werde> <dein> <Schmerz>."
]



export const konnen =  [
    "Ich <kann> dir nicht helfen.",
    "Du <kannst> es versuchen, aber es wird schwer.",
    "Er <kann> morgen nicht kommen.",
    "Wir <können> zusammen arbeiten, wenn du willst.",
    "Ihr <könnt> nach Hause gehen, sobald ihr fertig seid.",
    "Sie <können> es nicht erklären, aber es passiert immer."
  ]

  export const mussen =  [
    "Ich <muss> heute noch arbeiten.",
    "Du <musst> den Bericht fertigstellen.",
    "Er <muss> jetzt gehen, weil er einen Termin hat.",
    "Wir <müssen> pünktlich sein, sonst kommen wir zu spät.",
    "Ihr <müsst> das schon heute machen.",
    "Sie <müssen> noch viel lernen."
  ]

  export const durfen =  [
    "Ich <darf> heute nicht fernsehen.",
    "Du <darfst> nicht vergessen, dass du eine Verpflichtung hast.",
    "Er <darf> das nicht sagen.",
    "Wir <dürfen> hier nicht spielen.",
    "Ihr <dürft> euch das nicht entgehen lassen.",
    "Sie <dürfen> jetzt gehen, weil sie fertig sind."
  ]
  export const wollen = [
    "Ich <will> heute nicht arbeiten.",
    "Du <willst> mir etwas sagen, oder?",
    "Er <will> nicht mit uns kommen.",
    "Wir <wollen> bald in den Urlaub fahren.",
    "Ihr <wollt> das nicht verpassen.",
    "Sie <wollen> es nicht zugeben."
  ] 
  export const sollen = [
    "Ich <soll> heute früher kommen.",
    "Du <sollst> dich entscheiden.",
    "Er <soll> es ihr nicht erzählen.",
    "Wir <sollen> mehr üben, damit wir besser werden.",
    "Ihr <sollt> auf mich warten.",
    "Sie <sollen> rechtzeitig ankommen."
  ]
  export const mogen = [
    "Ich <mag> Schokolade nicht so sehr.",
    "Du <magst> ihn doch nicht, oder?",
    "Er <mag> es nicht, wenn es zu laut ist.",
    "Wir <mögen> den Sommer mehr als den Winter.",
    "Ihr <mögt> dieses Lied bestimmt auch.",
    "Sie <mögen> ihre Nachbarn nicht."
  ]
  export const mochten = [
    "Ich <möchte> ein Stück Kuchen essen.",
    "Du <möchtest> sicher noch etwas trinken.",
    "Er <möchte> heute nicht ausgehen.",
    "Wir <möchten> bald nach Hause fahren.",
    "Ihr <möchtet> das Buch bis morgen lesen.",
    "Sie <möchten> in den Urlaub fahren."
  ]

  export const modal = [konnen, mussen, durfen, mochten, mogen,sollen, wollen];