export const sentences = [
  '<Ich> <glaube>, dass <du> <recht> hast.',
  '<Er> <sagt>, dass <es> <regnen> wird.',
  '<Wir> <wissen>, dass <sie> <kommen> wird.',
  '<Ich> <hoffe>, dass <du> <gut> <schläfst>.',
  '<Sie> <hat> <Angst>, dass <er> <nicht> <kommt>.',
  '<Wir> <gehen> <nach> <Hause>, weil <es> <spät> ist.',
  '<Er> <konnte> <nicht> <spielen>, weil <er> <krank> war.',
  '<Wenn> <es> <schneit>, <bleibe> <ich> <zu> <Hause>.',
  '<Ich> <mag> <das> Lied, weil <es> <schön> ist.',
  '<Du> <musst> <lernen>, wenn <du> <bestehen> <willst>.',
  '<Ich> <freue> <mich>, dass <wir> <uns> <sehen>.',
  '<Wenn> <ich> <Zeit> habe, <lese> <ich> <ein> Buch.',
  '<Es> <ist> wichtig, dass <du> <früh> <kommst>.',
  '<Ich> <bin> glücklich, weil <du> <hier> bist.',
  '<Sie> <fragt>, ob <du> <mit> <kommst>.',
  '<Ich> <verstehe> <nicht>, warum <er> <so> <schüchtern> ist.',
  '<Du> <weißt>, dass <wir> <alle> <arbeiten> müssen.',
  '<Sie> <lässt> <mich> <wissen>, wann <sie> <kommt>.',
  '<Es> <stört> <mich>, dass <du> <zu> <spät> <bist>.',
  '<Wenn> <ich> <kann>, <helfe> <ich> <dir>.',
  '<Wir> <machen> <eine> Pause, weil <wir> <müde> sind.',
  '<Er> <hat> gesagt, dass <er> <nicht> <kommt>.',
  '<Wenn> <es> <schneit>, <gehen> <wir> <skifahren>.',
  '<Ich> <wünsche> mir, dass <wir> <urlaub> <machen>.',
  '<Wenn> <du> <Zeit> hast, <rufen> <mich> <an>.',
  '<Sie> <vergisst>, dass <wir> <ein> Treffen <haben>.',
  '<Es> <ist> schade, dass <du> <nicht> <kommen> <kannst>.',
  '<Wir> <sind> <glücklich>, dass <alles> <gut> <ist>.',
  '<Ich> <bin> traurig, weil <der> Film <langweilig> war.',
  '<Wenn> <er> <anruft>, <sage> <ihm>, dass <ich> <nicht> <da> bin.',
  '<Sie> <erzählt>, was <sie> <gestern> <gemacht> hat.',
  '<Ich> <weiß>, dass <das> <wichtig> ist.',
  '<Du> <fragst>, ob <ich> <helfen> <kann>.',
  '<Wenn> <es> <regnet>, <bleibe> <ich> <drinnen>.',
  '<Er> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Ich> <glaube>, dass <sie> <sind> <gute> <Freunde>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  '<Sie> <fragt>, ob <wir> <es> <nicht> <schaffen> können.',
  '<Ich> <verstehe>, dass <du> <dich> <nicht> <wohl> fühlst.',
  '<Wenn> <er> <schwimmen> <kann>, <geht> <er> <ins> <Schwimmbad>.',
  '<Es> <interessiert> <mich>, ob <du> <kaufen> <willst>.',
  '<Du> <musst> <schlafen>, wenn <du> <müde> <bist>.',
  '<Wenn> <ich> <gehe>, <kann> <ich> <dich> <anrufen>.',
  '<Wir> <sehen> <uns> <wieder>, wenn <du> <zurück> <kommst>.',
  '<Ich> <freue> mich, dass <wir> <uns> <treffen>.',
  '<Du> <weißt>, dass <sie> <nicht> <schüchtern> ist.',
  '<Sie> <lässt> <ihre> <Freunde> <wissen>, dass <sie> <kommt>.',
  '<Ich> <bin> mir sicher, dass <es> <funktioniert>.',
  '<Wenn> <du> <mich> <brauchst>, <ruf> <mich> <an>.',
  '<Er> <fragt>, ob <ich> <etwas> <mitbringen> <soll>.',
  '<Wir> <wissen>, dass <es> <nicht> <einfach> ist.',
  '<Ich> <verstehe>, warum <sie> <traurig> ist.',
  '<Wenn> <du> <das> <nicht> <magst>, <sag> <es> <mir>.',
  '<Sie> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Wenn> <ich> <zu> <spät> <bin>, <warte> <auf> <mich>.',
  '<Wir> <könnten> <essen>, wenn <du> <hunger> <hast>.',
  '<Ich> <mag> <den> Film, auch wenn <es> <langweilig> <ist>.',
  '<Sie> <will> <wissen>, was <wir> <machen> <werden>.',
  '<Er> <sagt>, dass <wir> <schon> <gehen> <können>.',
  '<Wenn> <du> <das> <brauchst>, <sag> <es> <mir>.',
  '<Ich> <freue> mich, wenn <du> <kommst>.',
  '<Wir> <gehen>, auch wenn <es> <regnet>.',
  '<Sie> <erzählt>, dass <sie> <neue> <Freunde> <gefunden> <hat>.',
  '<Wenn> <es> <nicht> <regnet>, <gehen> <wir> <spazieren>.',
  '<Er> <glaubt>, dass <wir> <es> <schaffen> <werden>.',
  '<Ich> <verstehe>, dass <du> <nicht> <kommst>.',
  '<Wenn> <wir> <fertig> <sind>, <können> <wir> <gehen>.',
  '<Sie> <sagt>, dass <sie> <müde> <ist>.',
  '<Du> <weißt>, dass <ich> <nicht> <gehe>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  '<Er> <hat> gesagt, dass <er> <nicht> <kommt>.',
  '<Wenn> <es> <schneit>, <gehen> <wir> <skifahren>.',
  '<Ich> <wünsche> mir, dass <wir> <urlaub> <machen>.',
  '<Wenn> <du> <Zeit> hast, <rufen> <mich> <an>.',
  '<Sie> <vergisst>, dass <wir> <ein> Treffen <haben>.',
  '<Es> <ist> schade, dass <du> <nicht> <kommen> <kannst>.',
  '<Wir> <sind> <glücklich>, dass <alles> <gut> <ist>.',
  '<Ich> <bin> traurig, weil <der> Film <langweilig> war.',
  '<Wenn> <er> <anruft>, <sage> <ihm>, dass <ich> <nicht> <da> bin.',
  '<Sie> <erzählt>, was <sie> <gestern> <gemacht> hat.',
  '<Ich> <weiß>, dass <das> <wichtig> ist.',
  '<Du> <fragst>, ob <ich> <helfen> <kann>.',
  '<Wenn> <es> <regnet>, <bleibe> <ich> <drinnen>.',
  '<Er> <findet>, dass <das> <eine> gute Idee <ist>.',
  '<Ich> <glaube>, dass <sie> <sind> <gute> <Freunde>.',
  '<Wir> <essen>, während <wir> <fernsehen>.',
  "<Ich> <freue> mich, dass <wir> <zusammen> <arbeiten>.",
  "<Er> <hat> gesagt, dass <er> <morgen> <kommt>.",
  "<Wenn> <du> <mich> <brauchst>, <kannst> <du> <anrufen>.",
  "<Sie> <schreibt>, weil <sie> <sehr> <beschäftigt> <ist>.",
  "<Ich> <finde> es schade, dass <du> <nicht> <mit> <kommen> <kannst>.",
  "<Wenn> <wir> <früh> <gehen>, <kommen> <wir> <rechtzeitig> <an>.",
  "<Sie> <hat> gesagt, dass <sie> <einen> neuen Job <hat>.",
  "<Wenn> <du> <schwimmen> <gehst>, <nehme> <ich> <mein> <Buch> <mit>.",
  "<Ich> <freue> mich, dass <du> <mir> <hilfst>.",
  "<Er> <denkt>, dass <wir> <es> <schaffen> <können>.",
  "<Wenn> <es> <schneit>, <möchte> <ich> <eine> Schneeballschlacht.",
  "<Wir> <essen> <gerne>, während <wir> <fernsehen>.",
  "<Ich> <mag> die Stadt, auch wenn <sie> <sehr> <laut> <ist>.",
  "<Sie> <fragt>, warum <du> <so> <traurig> <bist>.",
  "<Ich> <bin> froh, dass <wir> <uns> <treffen>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <gehen>.",
  "<Er> <sagt>, dass <er> <das> <nicht> <verstanden> <hat>.",
  "<Wenn> <ich> <fertig> <bin>, <gehe> <ich> <nach> <Hause>.",
  "<Wir> <glauben>, dass <es> <eine> gute Entscheidung <ist>.",
  "<Ich> <hoffe>, dass <du> <es> <verstehst>.",
  "<Wenn> <sie> <müde> <ist>, <schläft> <sie> <ein>.",
  "<Er> <sagt>, dass <es> <eine> gute Idee <ist>.",
  "<Wenn> <du> <Zeit> hast, <kannst> <du> <mir> <helfen>.",
  "<Wir> <gehen> <nach> <Hause>, weil <wir> <hungrig> <sind>.",
  "<Ich> <mag> es, wenn <du> <lächelst>.",
  "<Er> <will> wissen, ob <du> <kommst>.",
  "<Wenn> <es> <regnet>, <nehmen> <wir> <einen> Regenschirm.",
  "<Sie> <hat> <gesagt>, dass <sie> <nicht> <essen> <will.",
  "<Ich> <verstehe>, dass <es> <schwierig> <ist>.",
  "<Wenn> <wir> <gehen>, <wirst> <du> <verpassen>, was <passiert>.",
  "<Er> <hat> <gesagt>, dass <er> <seine> Meinung <ändern> <wird>.",
  "<Ich> <finde> es wichtig, dass <wir> <gemeinsam> <arbeiten>.",
  "<Sie> <freut> sich, dass <wir> <es> <geschafft> <haben>.",
  "<Wenn> <ich> <nicht> <komme>, <werde> <du> <allein> <sein>.",
  "<Er> <denkt>, dass <das> <eine> gute Gelegenheit <ist>.",
  "<Ich> <liebe> es, wenn <du> <lachst>.",
  "<Wenn> <du> <froh> <bist>, <singst> <du> <immer>.",
  "<Wir> <glauben>, dass <wir> <alle> <gemeinsam> <stark> <sind>.",
  "<Wenn> <es> <schneit>, <könnten> <wir> <schlittschuhlaufen>.",
  "<Er> <sagt>, dass <er> <die> Prüfung <bestehen> <wird>.",
  "<Wenn> <du> <mich> <fragst>, <kannst> <du> <es> <wissen>.",
  "<Ich> <bin> froh, dass <wir> <das> <geschafft> <haben>.",
  "<Wenn> <es> <warm> <ist>, <gehen> <wir> <zum> <Strand>.",
  "<Sie> <fragt>, ob <wir> <heute> <spielen> <wollen>.",
  "<Ich> <freue> <mich>, dass <wir> <uns> <treffen>.",
  "<Wenn> <ich> <gehe>, <werde> <ich> <es> <sagen>.",
  "<Er> <sagt>, dass <wir> <es> <versuchen> <sollen>.",
  "<Wenn> <sie> <kommt>, <werde> <ich> <glücklich> <sein>.",
  "<Ich> <verstehe>, dass <du> <angst> <hast>.",
  "<Wenn> <wir> <fertig> <sind>, <könnten> <wir> <essen>.",
  "<Sie> <denkt>, dass <wir> <es> <nicht> <schaffen> <können>.",
  "<Ich> <finde>, dass <das> <interessant> <ist>.",
  "<Wenn> <es> <kalt> <ist>, <ziehe> <ich> <meinen> <Mantel> <an>.",
  "<Er> <hofft>, dass <es> <bald> <aufhört> <zu> <regnen>.",
  "<Ich> <freue> mich, dass <wir> <bald> <kommen> <werden>.",
  "<Wenn> <du> <ein> Problem <hast>, <sag> <es> <mir>.",
  "<Wir> <glauben>, dass <das> <eine> gute Chance <ist>.",
  "<Ich> <verstehe>, wenn <du> <müde> <bist>.",
  "<Wenn> <es> <draußen> <warm> <ist>, <gehen> <wir> <spazieren>.",
  "<Sie> <sagt>, dass <wir> <bald> <gehen> <können>.",
  "<Ich> <freue> mich, wenn <du> <kommst>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <gehen>.",
  "<Er> <denkt>, dass <es> <eine> gute Idee <ist>.",
  "<Wenn> <ich> <fertig> <bin>, <gehe> <ich> <nach> <Hause>.",
  "<Wir> <glauben>, dass <wir> <es> <schaffen> <werden>.",
  "<Ich> <hoffe>, dass <du> <mich> <besuchst>.",
  "<Wenn> <du> <nicht> <kommst>, <werde> <ich> <allein> <sein>.",
  "<Er> <sagt>, dass <es> <eine> gute Entscheidung <ist>.",
  "<Wenn> <ich> <kann>, <helfe> <ich> <dir>.",
  "<Wir> <essen>, während <wir> <fernsehen>.",
  "<Ich> <mag> es, wenn <du> <lächelst>.",
  "<Er> <fragt>, ob <ich> <mit> <kommen> <kann>.",
  "<Wenn> <es> <regnet>, <könnten> <wir> <ein> <Tee> <trinken>.",
  "<Sie> <hat> gesagt, dass <sie> <nicht> <kommt>.",
  "<Ich> <verstehe>, dass <es> <nicht> <einfach> <ist>.",
  "<Wenn> <wir> <gehen>, <wirst> <du> <verpassen>, was <passiert>.",
  "<Er> <hat> <gesagt>, dass <er> <seine> Meinung <ändern> <wird>.",
  "<Ich> <finde> es wichtig, dass <wir> <gemeinsam> <arbeiten>.",
  "<Sie> <freut> sich, dass <wir> <es> <geschafft> <haben>.",
  "<Wenn> <ich> <nicht> <komme>, <werde> <du> <allein> <sein>.",
  "<Er> <denkt>, dass <das> <eine> gute Gelegenheit <ist>.",
  "<Ich> <liebe> es, wenn <du> <lachst>."
];
